# Setup
title:               Coffee and Contemplation
tagline:             'A developer blog'
description:         'A blog attempting to journal my learnings'
url:                 https://coffeeandcontemplation.dev
baseurl:             ''
paginate:            5
permalink:           pretty
tag_page:            'tag/'

# About/contact
author:
  name:              coffee and contemplation
  url:               coffeeandcontemplation.github.io
  #email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-FG8YL6SVEH
